import {
  VolumeX,
  Volume2,
  BookOpen,
  ScrollText,
  LogOut,
  Globe,
  ChevronDown,
  History,
  Trophy,
  Award,
  Medal,
  Gift,
  Settings,
  Share2,
  Users,
  User,
  Crown,
  Hourglass,
  Timer,
  Star,
  Circle,
  Dices,
  MessageCircle,
  Info,
  Lock,
  RotateCcw,
  Zap,
  Smile,
  Frown,
  Swords,
  ArrowLeft,
  ArrowRight,
  Ellipsis,
  X,
  FileText,
  Menu,
} from "lucide-react";

export const DYUT_ICONS = {
  soundMuted: VolumeX,
  soundOn: Volume2,
  howToPlay: BookOpen,
  rules: ScrollText,
  rulesFallback: FileText,
  exit: LogOut,
  language: Globe,
  dropdown: ChevronDown,

  history: History,
  leaderboard: Trophy,
  achievements: Award,
  medal: Medal,
  rewards: Gift,
  settings: Settings,

  shareMatch: Share2,
  inviteFriend: Users,
  profileFallback: User,

  currentTurn: Crown,
  timer: Hourglass,
  timerAlt: Timer,
  score: Star,
  playerStatus: Circle,

  dice: Dices,
  rollQueue: History,
  chat: MessageCircle,
  info: Info,

  privateMatch: Lock,
  resumeOffline: RotateCcw,
  quickMode: Zap,
  easyDifficulty: Smile,
  hardDifficulty: Frown,
  battle: Swords,

  back: ArrowLeft,
  next: ArrowRight,
  more: Ellipsis,
  close: X,
  menu: Menu,
} as const;
